INSERT INTO tasks (ID, DESCRIPTION, COMPLETED, CREATION_DATE, PRIORITY_VALUE) VALUES ('28830', 'Update local repositories', TRUE, SYSDATE(), 300);
INSERT INTO subtasks (ID, DESCRIPTION, START_DATE, END_DATE, FK_TASK) VALUES ('1', 'Subtask - Search dependencies', SYSDATE(), SYSDATE()+1, 28830);
INSERT INTO subtasks (ID, DESCRIPTION, START_DATE, END_DATE, FK_TASK) VALUES ('2', 'Subtask - Compile dependencies', SYSDATE(), SYSDATE()+1, 28830);
INSERT INTO TASKS (ID, DESCRIPTION, COMPLETED, CREATION_DATE, PRIORITY_VALUE) VALUES ('28831', 'Run quality control', FALSE, SYSDATE, 100);